### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#141]
Happens sometimes when switching between fragments and then returning to the RecipeFragment. It's weird because it only occasionally happens and it's almost completely random.

Will crash the app.

```E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.group4sweng.scranplan, PID: 24620
    java.lang.IllegalStateException: Fragment RecipeFragment{eb3a096} (2f8c9779-9c64-437c-82b7-23d2a92d5d94)} not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
        at androidx.fragment.app.Fragment.getResources(Fragment.java:869)
        at androidx.fragment.app.Fragment.getString(Fragment.java:891)
        at com.group4sweng.scranplan.SearchFunctions.RecipeFragment.loadNativeAds(RecipeFragment.java:812)
        at com.group4sweng.scranplan.SearchFunctions.RecipeFragment.access$300(RecipeFragment.java:60)
        at com.group4sweng.scranplan.SearchFunctions.RecipeFragment$5.onComplete(RecipeFragment.java:506)
        at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)```

Seems to crash here.
![image](https://user-images.githubusercontent.com/46009144/83449153-087af600-a44b-11ea-84e9-e74c91c99f7c.png)

**Comment by nathanbillis** [comment]
just fixed

**Comment by profjb58** [comment]
Oh brill.

**Comment by nathanbillis** [comment]
not on master yet

**Comment by nathanbillis** [comment]
haha
