### ISSUE TITLE
Out Of Memory issue (Bitmap image files) - Recipe info fragment

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#52]
Happens when trying to load the recipe fragment for different recipes from the home screen.

**Start of the error**
`I/art: Alloc sticky concurrent mark sweep GC freed 15774(781KB) AllocSpace objects, 3(48KB) LOS objects, 8% free, 85MB/93MB, paused 1.220ms total 21.453ms
I/art: Clamp target GC heap from 101MB to 96MB
    Alloc partial concurrent mark sweep GC freed 2615(129KB) AllocSpace objects, 1(16KB) LOS objects, 11% free, 85MB/96MB, paused 1.007ms total 62.957ms
I/art: Clamp target GC heap from 101MB to 96MB
    Alloc concurrent mark sweep GC freed 519(45KB) AllocSpace objects, 0(0B) LOS objects, 11% free, 85MB/96MB, paused 1.007ms total 73.486ms
    Forcing collection of SoftReferences for 12MB allocation
I/art: Clamp target GC heap from 101MB to 96MB
    Alloc concurrent mark sweep GC freed 15(456B) AllocSpace objects, 0(0B) LOS objects, 11% free, 85MB/96MB, paused 1.068ms total 72.570ms
E/art: Throwing OutOfMemoryError "Failed to allocate a 12635196 byte allocation with 11297172 free bytes and 10MB until OOM"
I/art: Alloc sticky concurrent mark sweep GC freed 5(672B) AllocSpace objects, 0(0B) LOS objects, 8% free, 85MB/93MB, paused 1.007ms total 7.324ms
I/art: Clamp target GC heap from 101MB to 96MB
    Alloc partial concurrent mark sweep GC freed 6(192B) AllocSpace objects, 0(0B) LOS objects, 11% free, 85MB/96MB, paused 1.037ms total 62.988ms
I/art: Clamp target GC heap from 101MB to 96MB
    Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 11% free, 85MB/96MB, paused 1.007ms total 72.021ms
    Forcing collection of SoftReferences for 12MB allocation
I/art: Clamp target GC heap from 101MB to 96MB
    Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 11% free, 85MB/96MB, paused 976us total 72.326ms
E/art: Throwing OutOfMemoryError "Failed to allocate a 12635196 byte allocation with 11297076 free bytes and 10MB until OOM"
D/skia: --- allocation failed for scaled bitmap
D/AndroidRuntime: Shutting down VM
E/art: li.han, Prepare to dump hprof for OOM Error !
    li.han, Directory [/data/log] could not be write !`

**End of error**
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.group4sweng.scranplan, PID: 18270
    java.lang.OutOfMemoryError: Failed to allocate a 12635196 byte allocation with 11297076 free bytes and 10MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:837)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:656)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1037)
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:4056)
        at android.content.res.Resources.loadDrawable(Resources.java:3929)
        at android.content.res.Resources.getDrawable(Resources.java:1991)
        at android.content.res.Resources.getDrawable(Resources.java:1973)
        at android.content.Context.getDrawable(Context.java:409)
        at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:454)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:144)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
        at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
        at androidx.appcompat.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:59)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:78)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
        at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:187)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:107)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:732)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
        at com.group4sweng.scranplan.RecipeInfo.RecipeInfoFragment.onCreateView(RecipeInfoFragment.java:116)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6934)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)`

**Comment by profjb58** [comment]
I'm testing on an old device. Samsung J3 to make sure it works on multiple devices so there is a chance the memory for the fragment isn't being freed once the user returns. I'll wipe the memory of the device to see if this is true.

**Comment by profjb58** [comment]
I've made some image helper functions on the 'A4 & A11 User Profile class' if anyone wants to grab those. (The file in the 'Helper' folder) that can check the extension and size of an image file from a Uri.

**Comment by nathanbillis** [comment]
@profjb58 would be useful if you could pull from the master and try again, and then chuck up the device details too

**Comment by profjb58** [comment]
So i'm an absolute dope and forgot to add an SD card or SIM card. Was exceeding max storage of less than 1mb -_-. Apologies.

**Comment by profjb58** [comment]
Duplicate of #93
