### ISSUE TITLE
Screen rotation issues

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#69]
Rotating the screen on the main recipe page causes the app to crash. 
There are a number of issues presented when rotating the screen. For e.g. there technically 2 different views so you have to pass info between them otherwise the following can happen.

We can just fix this by forcing the recipe screen so it can't be displayed in landscape within the android manifests file. I did do this before but it got removed for some reason.

I'm assuming because we wanted it to be displayed in landscape, but tbf it looks pretty bad in landscape atm so it would need to be re-designed as well for that orientation.
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.group4sweng.scranplan, PID: 31088
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.group4sweng.scranplan/com.group4sweng.scranplan.Home}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.group4sweng.scranplan.RecipeFragment: could not find Fragment constructor
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5046)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4955)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7078)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.group4sweng.scranplan.RecipeFragment: could not find Fragment constructor
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
        at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at com.group4sweng.scranplan.Home.onCreate(Home.java:104)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5046) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4955) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7078) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
     Caused by: java.lang.NoSuchMethodException: com.group4sweng.scranplan.RecipeFragment.<init> []
        at java.lang.Class.getConstructor0(Class.java:2328)
        at java.lang.Class.getConstructor(Class.java:1725)
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390) 
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74) 
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454) 
        at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196) 
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287) 
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106) 
        at com.group4sweng.scranplan.Home.onCreate(Home.java:104) 
        at android.app.Activity.performCreate(Activity.java:7327) 
        at android.app.Activity.performCreate(Activity.java:7318) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5046) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4955) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7078) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) ```

**Comment by profjb58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Landscape screen rotation issue](https://trello.com/c/qaEEKG6L/72-landscape-screen-rotation-issue)
