### ISSUE TITLE
PresentationTextView countdown timer

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#77]
Countdown timer is throwing an error from within the PresentationTextView class.
This isn't the same countdown timer i've just finished (the audio one).
I think the jist of the error is it dosen't exist.

I think James Clawley and Nathan mainly worked on the presentation so just tagging u guys.

```java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.CountDownTimer.cancel()' on a null object reference
        at com.group4sweng.scranplan.Presentation.Views.PresentationTextView.stopTimers(PresentationTextView.java:169)
W/System.err:     at com.group4sweng.scranplan.Presentation.PresentationSlide.hide(PresentationSlide.java:49)
        at com.group4sweng.scranplan.Presentation.Presentation.toSlide(Presentation.java:410)
        at com.group4sweng.scranplan.Presentation.Presentation.access$000(Presentation.java:70)
        at com.group4sweng.scranplan.Presentation.Presentation$2.onItemSelected(Presentation.java:269)
        at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
        at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
        at android.widget.AdapterView.access$300(AdapterView.java:55)
        at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)```

**Comment by profjb58** [comment]
Can be replicated by loading any recipe and entering the presentation view.

**Comment by profjb58** [comment]
If you can't replicate it from that try loading the ultimate spaghetti carbonara recipe since that is the one i'm using atm for testing.

**Comment by profjb58** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PresentationTextView countdown timer Null object reference](https://trello.com/c/WTd1McGu/75-presentationtextview-countdown-timer-null-object-reference)

**Comment by nathanbillis** [comment]
@jamesclawley do you know anything about this?

**Comment by profjb58** [comment]
It might be fixed by now. This was posted a very long time ago.
