### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by profjb58** [SWEngGroup4/scranplan#93]
The out of memory error has re-surfaced except this time it's on the emulator which is a bit more worrying. Again an issue with older devices not having enough memory/storager available to display the bitmap images.
The bitmap in this case seems to be 45mb which is very large for a recipe image so restrictions into what you can import into the recipe thing need to be implemented if they haven't already

- Android version 5.0 used (lollipop)
- Using the original Google Pixel phone.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.group4sweng.scranplan, PID: 3690
    java.lang.OutOfMemoryError: Failed to allocate a 45158412 byte allocation with 4194304 free bytes and 25MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:973)
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2423)
        at android.content.res.Resources.loadDrawable(Resources.java:2330)
        at android.content.res.Resources.getDrawable(Resources.java:758)
        at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:175)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1017)
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2418)
        at android.content.res.Resources.loadDrawable(Resources.java:2330)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
        at android.view.View.<init>(View.java:3730)
        at android.widget.TextView.<init>(TextView.java:634)
        at android.widget.Button.<init>(Button.java:111)
        at android.widget.CompoundButton.<init>(CompoundButton.java:81)
        at android.widget.CheckBox.<init>(CheckBox.java:72)
        at android.widget.CheckBox.<init>(CheckBox.java:68)
        at androidx.appcompat.widget.AppCompatCheckBox.<init>(AppCompatCheckBox.java:69)
        at androidx.appcompat.widget.AppCompatCheckBox.<init>(AppCompatCheckBox.java:65)
        at androidx.appcompat.app.AppCompatViewInflater.createCheckBox(AppCompatViewInflater.java:212)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:127)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:180)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at com.group4sweng.scranplan.Social.PostPage.onCreateView(PostPage.java:125)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
    	at androidx.fragment.```

**Comment by profjb58** [comment]
To replicate:
- Upload a recipe when posting in the feed. In this case I think I used pan fried chicken and mushroom sauce.

**Comment by nathanbillis** [comment]
Had a look on Firebase and the image isn't 45MB it's just under 45kB [![Image from Gyazo](https://i.gyazo.com/e047e74d96a00f7ecad730f4e063e732.png)](https://gyazo.com/e047e74d96a00f7ecad730f4e063e732)

**Comment by profjb58** [comment]
Think it might be an issue app wise instead which more and more images getting loaded in and none getting de-allocated.

**Comment by profjb58** [comment]
Might be worth going through all the resources we have and checking if the image file size is quite large or not.

**Comment by profjb58** [comment]
Either way it's not really related specifically to #91  from what I can tell

**Comment by nathanbillis** [comment]
> Think it might be an issue app wise instead which more and more images getting loaded in and none getting de-allocated.

Running the app with memory monitor open to check this.

**Comment by nathanbillis** [comment]
> Think it might be an issue app wise instead which more and more images getting loaded in and none getting de-allocated.

yep just ran a check and it's not this.

**Comment by profjb58** [comment]
I’ll have a look and see if it’s to do with my specific instance or version of the emulator.

**Comment by nathanbillis** [comment]
just ran with lollypop on nexus 4 emulator with no issues

**Comment by profjb58** [comment]
So, it is definately a memory allocation issue.
The limit for the old device is 500mb and it's getting very close to the threshold, just crashed again.
Memory is stacking up and not being re-allocated as well when moving between screens.
It's specifically an issue with #91 because it dosen't de-allocate memory from the recipe info page, so that data is stored, then the feed images and then once you open the comments and have the same image again it causes a crash.

Advanced de-bugging is not available on older devices but i'll try that as well.

![image](https://user-images.githubusercontent.com/46009144/82478862-70cfec00-9ac9-11ea-84c6-a4165658eb16.png)

**Comment by nathanbillis** [comment]
[![Image from Gyazo](https://i.gyazo.com/b38c991696f92835883f320c099acb7e.gif)](https://gyazo.com/b38c991696f92835883f320c099acb7e)

**Comment by nathanbillis** [comment]
[![Image from Gyazo](https://i.gyazo.com/cc53d9f8b25adc73c2bb4dda718fde52.gif)](https://gyazo.com/cc53d9f8b25adc73c2bb4dda718fde52)

https://i.gyazo.com/cc53d9f8b25adc73c2bb4dda718fde52.mp4

**Comment by profjb58** [comment]
So it isn't quite as bad on that device but it's still reaching 330mb.

**Comment by profjb58** [comment]
For the sake of time. Wont be fixed currently. Only seems to be an issue on the google pixel on API 21 and under very specific conditions.

Quote from nathan:
```so the issue is the feed fragment keeps the images in cache for speed when you click on them, when you click off and then try to attach a new recipe it crashes```
