### ISSUE TITLE
Chef info causing crashes when data is missing

### ISSUE THREAD

**Issue by jamesclawley** [SWEngGroup4/scranplan#96]
If a chef's account is deleted (or in the future if a recipe is removed from an account) the recipe info fragment crashes when attempting to display the chefs name.
Need a simple handler to display a '[deleted]' string or something similar to avoid this.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.group4sweng.scranplan, PID: 9155
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
        at com.group4sweng.scranplan.RecipeInfo.RecipeInfoFragment$6$1.onComplete(RecipeInfoFragment.java:432)
        at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7777)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)`

**Comment by nathanbillis** [comment]
[![Image from Gyazo](https://i.gyazo.com/1cf16746ddd701fc924e12a6fbaed1d8.png)](https://gyazo.com/1cf16746ddd701fc924e12a6fbaed1d8)

**Comment by jamesclawley** [comment]
Fixed with #159 - waiting for merge
